# Generated by Django 5.0.4 on 2024-04-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_employeeanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='answer1',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='answer2',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='answer3',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='answer4',
            new_name='question4',
        ),
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='answer5',
            new_name='question5',
        ),
    ]
